# Generated by Django 5.1.4 on 2025-03-04 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('school', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('math_score', models.FloatField(blank=True, null=True)),
                ('english_score', models.FloatField(blank=True, null=True)),
                ('science_score', models.FloatField(blank=True, null=True)),
                ('history_score', models.FloatField(blank=True, null=True)),
                ('attendance_rate', models.FloatField(blank=True, null=True)),
                ('study_hours_per_week', models.FloatField(blank=True, null=True)),
                ('household_income', models.FloatField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')], null=True)),
                ('school_type', models.IntegerField(blank=True, choices=[(0, 'Private'), (1, 'Public')], null=True)),
                ('location', models.IntegerField(blank=True, choices=[(0, 'Rural'), (1, 'Urban')], null=True)),
                ('parental_education_level', models.IntegerField(blank=True, choices=[(0, 'Primary'), (1, 'Secondary'), (2, 'Tertiary')], null=True)),
                ('internet_access', models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True)),
                ('parental_career', models.IntegerField(blank=True, choices=[(0, 'Arts'), (1, 'Business'), (2, 'Education'), (3, 'Healthcare'), (4, 'Technology')], null=True)),
                ('extracurricular_activity', models.IntegerField(blank=True, choices=[(0, 'Entrepreneurship Club'), (1, 'Music'), (2, 'None'), (3, 'Science Club'), (4, 'Sports')], null=True)),
                ('interest', models.IntegerField(blank=True, choices=[(0, 'Arts'), (1, 'Business'), (2, 'Healthcare'), (3, 'Humanities'), (4, 'STEM')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('predicted_subject', models.IntegerField(choices=[(0, 'Arts'), (1, 'Business'), (2, 'Healthcare'), (3, 'Humanities'), (4, 'STEM')])),
                ('recommended_subjects', models.CharField(help_text='Comma-separated recommended subjects', max_length=255)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='recommender.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.prediction')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.studentprofile')),
            ],
        ),
    ]
